pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot-preview[bot]
      - status-success=Travis CI - Pull Request
      - status-success=Travis CI - Branch
      - status-success=security/snyk (binhonglee)
      - status-success=codecov/patch
      - status-success=codecov/project
    actions:
      merge:
        method: merge
