os:
  - linux
  - osx

language: c
node_js: stable
python: "3.8"

env:
  - BRANCH=1.0.6
  - BRANCH=1.2.0
  - BRANCH=stable

cache:
  directories:
    - "$HOME/.nimble/bin"
    - "$HOME/.choosenim"
    - "$HOME/.please"

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH
  - cd src/tsUtil
  - npm install
  - cd ../../
  - |
    if ! type -P choosenim &> /dev/null; then
      echo "Fresh install"
      export CHOOSENIM_CHOOSE_VERSION=$BRANCH
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
    else
      echo "Already installed"
      rm -rf $HOME/.choosenim/current
      choosenim update $BRANCH --latest
      choosenim $BRANCH
    fi
  - nimble -y build

script:
  - ./scripts/test.sh
  - cd src/tsUtil
  - npm run cover
  - cd ../../

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip3 install -r requirements.txt
  - ./pleasew --show_all_output genDocs

deploy:
  edge: true
  cleanup: false
  strategy: git
  provider: pages
  local_dir: site
  keep_history: true
  token: $GITHUB_TOKEN
  on:
    branch: devel
    condition:
      - "$(uname -s) = Darwin"
      - "$BRANCH = stable"
