os:
  - linux
  - osx

language: c
node_js: stable
python: "3.8"

cache:
  directories:
    - "$HOME/.nimble/bin"
    - "$HOME/.choosenim"

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH
  - cd src/tsUtil
  - npm install
  - cd ../../
  - |
    if ! type -P choosenim &> /dev/null; then
      export CHOOSENIM_CHOOSE_VERSION=$BRANCH
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
    fi
  - nimble -y build

script:
  - ./scripts/test.sh
  - cd src/tsUtil
  - npm run cover

after_success:
  - pip install -r requirements.txt
  - mkdocs build
  - bash <(curl -s https://codecov.io/bash)
