filegroup(
    name = "lang",
    srcs = [
        "defaults.nim",
        "goConfig.nim",
        "ktConfig.nim",
        "nimConfig.nim",
        "psqlConfig.nim",
        "pyConfig.nim",
        "tsConfig.nim",
    ],
    visibility = [
        "//src/main:files",
    ],
)
