# DO NOT MANUALLY EDIT THIS FILE
#
# This file is automatically generated based on the config files located in `examples/input/template/`.

from stones/cases import Case
import tables
import ../lib/tconfig

const COMMENT: string = "//"
const FILENAME: Case = Case.Pascal
const FILETYPE: string = "kt"
const IMPLEMENT_FORMAT: string = ": {#IMPLEMENT} "
const IMPORT_PATH_FORMAT: string = ""
const IMPORT_PATH_TYPE: ImportPathType = ImportPathType.Never
const IMPORT_PATH_PREFIX: string = ""
const IMPORT_PATH_SEPARATOR: char = '/'
const IMPORT_PATH_LEVEL: int = 0
const PARSE_FORMAT: string = ""
const INTERFACE_SUPPORTED: bool = true
const PARAM_FORMAT: string = "{#PARAM_NAME}: {#PARAM_TYPE}"
const PARAM_JOINER: string = ", "
const PRE_INDENT: bool = true
const INDENTATION_SPACING: string = "  "

const TEMPLATE_STRUCT: string = """
package {#1}
// #BEGIN_IMPORT

// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT

// {#COMMENT}
class {#NAME} {#IMPLEMENT}{
// #BEGIN_VAR
  // #VAR var {#VARNAME_CAMEL}: {#TYPE} = {#TYPE_INIT}
// #END_VAR

// #BEGIN_JSON
  fun toJsonKey(key: string): string {
    when (key) {
      // #JSON "{#VARNAME_CAMEL}" -> return "{#VARNAME_JSON}"
      else -> return key
    }
  }
// #END_JSON
// #BEGIN_FUNCTIONS
// #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS
}

"""

const TEMPLATE_ENUM: string = """
package {#1}

// #BEGIN_VAR
enum class {#NAME} {
  // #VAR {#VARNAME_PASCAL}
}
// #END_VAR

"""

const TEMPLATE_INTERFACE: string = """
package {#1}
// #BEGIN_IMPORT

// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT

// {#COMMENT}
interface {#NAME} {#IMPLEMENT}{
// #BEGIN_FUNC
  // #FUNC fun {#FUNCNAME_CAMEL}({#PARAMS}): {#TYPE}
// #END_FUNC
// #BEGIN_FUNCTIONS

// #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS
}

"""

const TEMPLATE_LOGGER: string = """

"""

let TYPES: Table[string, TypeInterpreter] = {
  "dbl": initTypeInterpreter("dbl", "Double", "", "0", ""),
  "void": initTypeInterpreter("void", "Unit", "", "", ""),
  "bool": initTypeInterpreter("bool", "Boolean", "", "false", ""),
  "flt": initTypeInterpreter("flt", "Float", "", "0", ""),
  "date": initTypeInterpreter("date", "Date", "", "Date()", ""),
  "str": initTypeInterpreter("str", "String", "", "\"\"", ""),
  "!imported": initTypeInterpreter("!imported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", ""),
  "int": initTypeInterpreter("int", "Int", "", "0", ""),
  "!unimported": initTypeInterpreter("!unimported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", ""),
}.toTable()

let CUSTOM_TYPES: Table[string, CustomTypeInterpreter] = {
  "Map<": interpretType(
    initTypeInterpreter("Map<{TYPE1},{TYPE2}>", "HashMap<{TYPE1}, {TYPE2}>", "", "hashMapOf<{TYPE1}, {TYPE2}>()", "")
  ),
  "[]": interpretType(
    initTypeInterpreter("[]{TYPE}", "ArrayList<{TYPE1}>", "", "arrayListOf<{TYPE1}>()", "")
  ),
}.toTable()

let KT_CONFIG*: TConfig = initTConfig(
  cmt = COMMENT,
  ct = CUSTOM_TYPES,
  c = FILENAME,
  ft = FILETYPE,
  ifmt = IMPLEMENT_FORMAT,
  ipfmt = IMPORT_PATH_FORMAT,
  ipt = IMPORT_PATH_TYPE,
  pfx = IMPORT_PATH_PREFIX,
  sep = IMPORT_PATH_SEPARATOR,
  level = IMPORT_PATH_LEVEL,
  isp = INDENTATION_SPACING,
  pi = PRE_INDENT,
  isup = INTERFACE_SUPPORTED,
  prmFmt = PARAM_FORMAT,
  prmJnr = PARAM_JOINER,
  pfmt = PARSE_FORMAT,
  temp = {
    "struct": TEMPLATE_STRUCT,
    "enum": TEMPLATE_ENUM,
    "interface": TEMPLATE_INTERFACE,
    "logger": TEMPLATE_LOGGER,
  }.toTable(),
  ty = TYPES,
)
