# DO NOT MANUALLY EDIT THIS FILE
#
# This file is automatically generated based on the config files located in `examples/input/template/`.

from stones/cases import Case
import tables
import ../lib/tconfig

const COMMENT: string = "//"
const FILENAME: Case = Case.Pascal
const FILETYPE: string = "kt"
const IMPLEMENT_FORMAT: string = ": {#IMPLEMENT} "
const IMPORT_PATH_FORMAT: string = ""
const IMPORT_PATH_TYPE: ImportPathType = ImportPathType.Never
const IMPORT_PATH_PREFIX: string = ""
const IMPORT_PATH_SEPARATOR: char = '/'
const IMPORT_PATH_LEVEL: int = 0
const PARSE_FORMAT: string = ""
const INTERFACE_SUPPORTED: bool = true
const PARAM_FORMAT: string = "{#PARAM_NAME}: {#PARAM_TYPE}"
const PARAM_JOINER: string = ", "
const PRE_INDENT: bool = true
const INDENTATION_SPACING: string = "  "

const TEMPLATE_STRUCT: string = """
package {#1}
// #BEGIN_IMPORT
// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// {#COMMENT}
@Serializable
@Parcelize
data class {#NAME}(
// #BEGIN_VAR
    // #VAR {#TYPE_PREFIX}
    // #VAR @SerialName(value = "{#VARNAME_JSON}")
    // #VAR var {#VARNAME_CAMEL}: {#TYPE},
    // #VAR {#TYPE_SUFFIX}
// #END_VAR
) : {#IMPLEMENT}Parcelable

"""

const TEMPLATE_ENUM: string = """
package {#1}

var val_{#NAME} = 0

// #BEGIN_VAR
enum class {#NAME}(val value: Int = val_{#NAME}++) {
    // #VAR {#VARNAME_PASCAL},
}
// #END_VAR

"""

const TEMPLATE_INTERFACE: string = """
package {#1}
// #BEGIN_IMPORT

// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT

// {#COMMENT}
interface {#NAME} {#IMPLEMENT}{
// #BEGIN_FUNC
  // #FUNC fun {#FUNCNAME_CAMEL}({#PARAMS}): {#TYPE}
// #END_FUNC
// #BEGIN_FUNCTIONS

// #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS
}

"""

let TYPES: Table[string, TypeInterpreter] = {
  "int": initTypeInterpreter("int", "Int", "", "0", "", "", ""),
  "str": initTypeInterpreter("str", "String", "", "\"\"", "", "", ""),
  "void": initTypeInterpreter("void", "Unit", "", "", "", "", ""),
  "date": initTypeInterpreter("date", "Instant", "kotlinx.datetime.Instant\nimport kotlinx.parcelize.TypeParceler", "Instant.now()", "", "@TypeParceler<Instant, InstantParceler>", ""),
  "!unimported": initTypeInterpreter("!unimported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", "", "", ""),
  "dbl": initTypeInterpreter("dbl", "Double", "", "0", "", "", ""),
  "bool": initTypeInterpreter("bool", "Boolean", "", "false", "", "", ""),
  "!imported": initTypeInterpreter("!imported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", "", "", ""),
  "flt": initTypeInterpreter("flt", "Float", "", "0", "", "", ""),
}.toTable()

let CUSTOM_TYPES: Table[string, CustomTypeInterpreter] = {
  "[]": interpretType(
    initTypeInterpreter("[]{TYPE}", "ArrayList<{TYPE1}>", "", "arrayListOf<{TYPE1}>()", "", "", "")
  ),
  "Map<": interpretType(
    initTypeInterpreter("Map<{TYPE1},{TYPE2}>", "HashMap<{TYPE1}, {TYPE2}>", "", "hashMapOf<{TYPE1}, {TYPE2}>()", "", "", "")
  ),
}.toTable()

let KT_CONFIG*: TConfig = initTConfig(
  cmt = COMMENT,
  ct = CUSTOM_TYPES,
  c = FILENAME,
  ft = FILETYPE,
  ifmt = IMPLEMENT_FORMAT,
  ipfmt = IMPORT_PATH_FORMAT,
  ipt = IMPORT_PATH_TYPE,
  pfx = IMPORT_PATH_PREFIX,
  sep = IMPORT_PATH_SEPARATOR,
  level = IMPORT_PATH_LEVEL,
  isp = INDENTATION_SPACING,
  pi = PRE_INDENT,
  isup = INTERFACE_SUPPORTED,
  prmFmt = PARAM_FORMAT,
  prmJnr = PARAM_JOINER,
  pfmt = PARSE_FORMAT,
  temp = {
    "struct": TEMPLATE_STRUCT,
    "enum": TEMPLATE_ENUM,
    "interface": TEMPLATE_INTERFACE,
  }.toTable(),
  ty = TYPES,
)
