# DO NOT MANUALLY EDIT THIS FILE
#
# This file is automatically generated based on the config files located in `examples/input/template/`.

from stones/cases import Case
import tables
import ../lib/tconfig

const COMMENT: string = "#"
const FILENAME: Case = Case.Lower
const FILETYPE: string = "py"
const IMPLEMENT_FORMAT: string = "{#IMPLEMENT}"
const IMPORT_PATH_FORMAT: string = "{#IMPORT}"
const IMPORT_PATH_TYPE: ImportPathType = ImportPathType.Absolute
const IMPORT_PATH_PREFIX: string = ""
const IMPORT_PATH_SEPARATOR: char = '.'
const IMPORT_PATH_LEVEL: int = 0
const PARSE_FORMAT: string = ""
const INTERFACE_SUPPORTED: bool = false
const PARAM_FORMAT: string = ""
const PARAM_JOINER: string = ""
const PRE_INDENT: bool = true
const INDENTATION_SPACING: string = "  "

const TEMPLATE_STRUCT: string = """
// #BEGIN_IMPORT
import json
// #IMPORT1 import {#IMPORT_1}
// #IMPORT2 from {#IMPORT_1} import {#IMPORT_2}
// #END_IMPORT

// #BEGIN_VAR
# {#COMMENT}
class {#NAME}({#IMPLEMENT}):
  // #VAR {#VARNAME_SNAKE}: {#TYPE} = {#TYPE_INIT}
// #END_VAR

  def __init__(self, data):
    self = json.loads(data)
// #BEGIN_FUNCTIONS
  // #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS

"""

const TEMPLATE_ENUM: string = """
from enum import Enum, auto

// #BEGIN_VAR
class {#NAME}(Enum):
  // #VAR {#VARNAME_PASCAL} = auto()
// #END_VAR

"""

const TEMPLATE_INTERFACE: string = """

"""

const TEMPLATE_LOGGER: string = """

"""

let TYPES: Table[string, TypeInterpreter] = {
  "dbl": initTypeInterpreter("dbl", "double", "", "0", ""),
  "bool": initTypeInterpreter("bool", "bool", "", "False", ""),
  "flt": initTypeInterpreter("flt", "float", "", "0", ""),
  "date": initTypeInterpreter("date", "datetime", "datetime:datetime", "datetime.now()", ""),
  "str": initTypeInterpreter("str", "str", "", "\"\"", ""),
  "!imported": initTypeInterpreter("!imported", "{#TYPE_PASCAL}", "", "new {#TYPE_PASCAL}()", ""),
  "int": initTypeInterpreter("int", "int", "", "0", ""),
  "!unimported": initTypeInterpreter("!unimported", "{#TYPE_PASCAL}", "", "new {#TYPE_PASCAL}()", ""),
}.toTable()

let CUSTOM_TYPES: Table[string, CustomTypeInterpreter] = {
  "Map<": interpretType(
    initTypeInterpreter("Map<{TYPE1},{TYPE2}>", "dict", "", "{}", "")
  ),
  "[]": interpretType(
    initTypeInterpreter("[]{TYPE}", "list", "", "[]", "")
  ),
}.toTable()

let PY_CONFIG*: TConfig = initTConfig(
  cmt = COMMENT,
  ct = CUSTOM_TYPES,
  c = FILENAME,
  ft = FILETYPE,
  ifmt = IMPLEMENT_FORMAT,
  ipfmt = IMPORT_PATH_FORMAT,
  ipt = IMPORT_PATH_TYPE,
  pfx = IMPORT_PATH_PREFIX,
  sep = IMPORT_PATH_SEPARATOR,
  level = IMPORT_PATH_LEVEL,
  isp = INDENTATION_SPACING,
  pi = PRE_INDENT,
  isup = INTERFACE_SUPPORTED,
  prmFmt = PARAM_FORMAT,
  prmJnr = PARAM_JOINER,
  pfmt = PARSE_FORMAT,
  temp = {
    "struct": TEMPLATE_STRUCT,
    "enum": TEMPLATE_ENUM,
    "interface": TEMPLATE_INTERFACE,
    "logger": TEMPLATE_LOGGER,
  }.toTable(),
  ty = TYPES,
)
