# DO NOT MANUALLY EDIT THIS FILE
#
# This file is automatically generated based on the config files located in `examples/input/template/`.

from stones/cases import Case
import tables
import ../lib/tconfig

const COMMENT: string = "//"
const FILENAME: Case = Case.Pascal
const FILETYPE: string = "swift"
const IMPLEMENT_FORMAT: string = ": {#IMPLEMENT} "
const IMPORT_PATH_FORMAT: string = ""
const IMPORT_PATH_TYPE: ImportPathType = ImportPathType.Never
const IMPORT_PATH_PREFIX: string = ""
const IMPORT_PATH_SEPARATOR: char = '/'
const IMPORT_PATH_LEVEL: int = 0
const PARSE_FORMAT: string = ""
const INTERFACE_SUPPORTED: bool = false
const PARAM_FORMAT: string = ""
const PARAM_JOINER: string = ""
const PRE_INDENT: bool = true
const INDENTATION_SPACING: string = "  "

const TEMPLATE_STRUCT: string = """
import Foundation
// #BEGIN_IMPORT
// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT

// {#COMMENT}
public struct {#NAME}: Codable, Identifiable {
// #BEGIN_VAR
  // #VAR public var {#VARNAME_JSON}: {#TYPE}
// #END_VAR
  
  public init(
// #BEGIN_CONSTRUCTOR
    // #CONSTRUCTOR {#VARNAME_JSON}: {#TYPE},
// #END_CONSTRUCTOR
  ) {
// #BEGIN_PARAMS
    // #PARAMS self.{#VARNAME_JSON} = {#VARNAME_JSON}
// #END_PARAMS
  }
  
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
// #BEGIN_JSON
    // #JSON self.{#VARNAME_JSON} = try container.decode({#TYPE}.self, forKey: .{#VARNAME_JSON})
// #END_JSON
  }
}

// #BEGIN_FUNCTIONS
  // #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS

"""

const TEMPLATE_ENUM: string = """
// #BEGIN_IMPORT
import Foundation
// #IMPORT1 import {#IMPORT_1}
// #END_IMPORT

// {#COMMENT}
public enum {#NAME}: Int {
// #BEGIN_VAR
  // #VAR case {#VARNAME_PASCAL}
// #END_VAR
}

"""

const TEMPLATE_INTERFACE: string = """

"""

let TYPES: Table[string, TypeInterpreter] = {
  "int": initTypeInterpreter("int", "Int", "", "0", "", "", ""),
  "str": initTypeInterpreter("str", "String", "", "\"\"", "", "", ""),
  "void": initTypeInterpreter("void", "Void", "", "", "", "", ""),
  "date": initTypeInterpreter("date", "Date", "", "Date.now()", "", "", ""),
  "!unimported": initTypeInterpreter("!unimported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", "", "", ""),
  "dbl": initTypeInterpreter("dbl", "Double", "", "0", "", "", ""),
  "bool": initTypeInterpreter("bool", "Boolean", "", "false", "", "", ""),
  "!imported": initTypeInterpreter("!imported", "{#TYPE_PASCAL}", "", "{#TYPE_PASCAL}()", "", "", ""),
  "flt": initTypeInterpreter("flt", "Float", "", "0", "", "", ""),
}.toTable()

let CUSTOM_TYPES: Table[string, CustomTypeInterpreter] = {
  "[]": interpretType(
    initTypeInterpreter("[]{TYPE}", "[{TYPE1}]", "", "[] as [{TYPE1}]", "", "", "")
  ),
  "Map<": interpretType(
    initTypeInterpreter("Map<{TYPE1},{TYPE2}>", "[{TYPE1}: {TYPE2}]", "", "[:] as [{TYPE1}: {TYPE2}]", "", "", "")
  ),
}.toTable()

let SWIFT_CONFIG*: TConfig = initTConfig(
  cmt = COMMENT,
  ct = CUSTOM_TYPES,
  c = FILENAME,
  ft = FILETYPE,
  ifmt = IMPLEMENT_FORMAT,
  ipfmt = IMPORT_PATH_FORMAT,
  ipt = IMPORT_PATH_TYPE,
  pfx = IMPORT_PATH_PREFIX,
  sep = IMPORT_PATH_SEPARATOR,
  level = IMPORT_PATH_LEVEL,
  isp = INDENTATION_SPACING,
  pi = PRE_INDENT,
  isup = INTERFACE_SUPPORTED,
  prmFmt = PARAM_FORMAT,
  prmJnr = PARAM_JOINER,
  pfmt = PARSE_FORMAT,
  temp = {
    "struct": TEMPLATE_STRUCT,
    "enum": TEMPLATE_ENUM,
    "interface": TEMPLATE_INTERFACE,
  }.toTable(),
  ty = TYPES,
)
