filegroup(
    name = 'lib',
    srcs = [
        'tconfig.nim',
        'tconstant.nim',
        'templatable.nim',
        'templating.nim',
        'winterface.nim',
        'wiutil.nim',
    ],
    visibility =  [
        '//src/main:files',
    ]
)
