filegroup(
    name = "lib",
    srcs = [
        "dbtconfig.nim",
        "tconfig.nim",
        "tempconst.nim",
        "templatable.nim",
        "templating.nim",
        "tutil.nim",
        "winterface.nim",
        "wiutil.nim",
    ],
    visibility = [
        "//src/main:files",
        "//src/main/staticlang:static",
    ],
)
