filegroup(
  name = 'lib',
  srcs = [
    'tconfig.nim',
    'tempconst.nim',
    'templatable.nim',
    'templating.nim',
    'tutil.nim',
    'winterface.nim',
    'wiutil.nim',
  ],
  visibility =  [
    '//src/main:files',
  ]
)
