filegroup(
    name = "genFiles",
    srcs = [
        "output/ts/Homework.ts",
        "output/ts/Student.ts",
        "output/ts/person/Emotion.ts",
    ],
    visibility = [
        "//src/tsUtil:mocha",
    ],
)
