subinclude('@pleasings//nim')

nim_binary(
    name = 'wings',
    main = 'wings.nim',
    srcs = [
        'wingspkg/core.nim',
        'wingspkg/plz.nim',
        'wingspkg/lang/go.nim',
        'wingspkg/lang/kt.nim',
        'wingspkg/lang/nim.nim',
        'wingspkg/lang/py.nim',
        'wingspkg/lang/ts.nim',
        'wingspkg/lib/config.nim',
        'wingspkg/lib/filename.nim',
        'wingspkg/lib/header.nim',
        'wingspkg/lib/varname.nim',
        'wingspkg/lib/wenum.nim',
        'wingspkg/lib/winterface.nim',
        'wingspkg/lib/wstruct.nim',
        'wingspkg/util/wiutil.nim',
    ],
    visibility = ['PUBLIC'],
)
