// #BEGIN_IMPORT
// #IMPORT2 import {#IMPORT_1} from '{#IMPORT_2}';
// #END_IMPORT

// {#COMMENT}
export default interface {#NAME_PASCAL} {#IMPLEMENT}{
// #BEGIN_FUNC
  // #FUNC {#FUNCNAME_CAMEL}({#PARAMS}): {#TYPE};
// #END_FUNC
// #BEGIN_FUNCTIONS

// #FUNCTIONS {#FUNCTIONS}
// #END_FUNCTIONS
}
