filegroup(
    name = "test_files",
    srcs = [
        "Homework.ts",
        "Student.ts",
        "person/Emotion.ts",
        "index.test.ts",
    ],
    visibility = [
        "//src/tsUtil:mocha",
    ],
)
